apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: futsal-pvc-staging
  namespace: futsal-staging
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      environment: staging
      app: futsal-app