apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foot-app-pv-ebs
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 10Gi