apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foot-app-ingress
  namespace: prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: foot.badr.cloud
      http:
        paths:
          - path: /.well-known/acme-challenge/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: cm-acme-http-solver-54q5p
                port:
                  number: 8089
          - path: /
            pathType: Prefix
            backend:
              service:
                name: foot-app-service
                port:
                  number: 6000
  tls:
    - hosts:
        - foot.badr.cloud
      secretName: foot-app-secret
