apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: futsal-pvc-dev
  namespace: futsal-dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      environment: dev
      app: futsal-app