apiVersion: v1
kind: PersistentVolume
metadata:
  name: foot-app-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/data/appsdata/foot"  # Remplacez par un chemin valide sur chaque nœud k3s
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "debtest"  # Remplacez par le nom de votre nœud k3s